[theme]
base = "dark"
primaryColor = "#ff073a"         # Rouge néon
backgroundColor = "#000000"      # Noir profond
secondaryBackgroundColor = "#0a0a0a"
textColor = "#39ff14"            # Vert fluo
font = "monospace"
